#cloud-config
groups:
  - ubuntu: [root,sys]
  - devops

users:
  - default
  - name: devops
    primary_group: devops
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false
    passwd: "${hashed_pass}"
  - name: ci-user
    primary_group: ci-user
    groups: sudo
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: false
    passwd: ${hashed_pass}


manage_etc_hosts: true

write_files:
  - path: /etc/multipath.conf
    content: |
      defaults {
          user_friendly_names yes
      }
      blacklist {
          devnode "^sd[a-z0-9]+"
      }

  - path: /etc/netplan/99-netcfg-vmware.yaml
    permissions: '0644'
    content: |
      # Generated by VMWare customization engine.
      network:
        version: 2
        renderer: networkd
        ethernets:
          ens192:
            dhcp4: no
            dhcp6: no
            addresses:
              - 10.100.105.99/24
            gateway4: ${vm_gw_ip_az1}

  - path: /root/template-ready.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      swapoff --all
      sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab
      sudo apt update
      sudo apt upgrade -y
      sudo apt install vim nfs-common -y
      sudo apt remove unattended-upgrades

bootcmd:
  - printf "[Resolve]\nDNS=8.8.8.8 8.8.4.4" > /etc/systemd/resolved.conf
  - [ systemctl, restart, systemd-resolved ]

runcmd:
  - [ sh, -c, 'sudo apt remove unattended-upgrades' ]
  - [ sh, -c, 'systemctl restart multipathd.service' ]
  - [ sh, -c, 'sudo rmmod floppy' ]
  - [ sh, -c, 'echo "blacklist floppy" | sudo tee /etc/modprobe.d/blacklist-floppy.conf' ]
  - [ sh, -c, 'sudo dpkg-reconfigure initramfs-tools' ]
  - [ sh, -c, 'sed -i "s/^PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config.d/60-cloudimg-settings.conf' ]
  - [ sh, -c, 'systemctl restart ssh' ]
  - [ sh, -c, 'echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf' ]
  - [ sh, -c, 'sysctl -p' ]
  - [ sh, -c, 'netplan apply' ]
  - [ sh, -c, '/root/template-ready.sh' ]
  - [ sh, -c, 'timedatectl set-timezone Asia/Baku' ]
