apiVersion: v1
kind: Service
metadata:
  name: rke2-ingress-nginx-controller-lb
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: 30080
    - name: https
      port: 443
      protocol: TCP
      nodePort: 30443
    - name: webhook
      port: 8443
      protocol: TCP
      nodePort: 31243
  selector:
    app.kubernetes.io/instance: rke2-ingress-nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
