- job_name: git-exporter
  static_configs:
    - targets:
        - 10.0.211.2:9100
- job_name: blackbox
  scrape_interval: 30s
  metrics_path: /probe
  params:
    module: [http_2xx] # Look for a HTTP 200 response.
  static_configs:
    - targets:
        #    - https://ui.cloud.sima.az:30443
        - https://git.azintelecom.az
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: prometheus-community-prometheus-blackbox-exporter:9115  # blackbox
    - source_labels: [ __meta_dns_name ]
      target_label: __param_hostname  # Make domain name become 'Host' header for probe requests
    - source_labels: [ __meta_dns_name ]
      target_label: vhost  # and store it in 'vhost' label
