- job_name: 'node-exporter'
  static_configs:
    - targets:
        - ${nfs_ip}:9100
        - 10.100.104.3:9100

- job_name: 'vmware-vcenter-exporter'
  scrape_interval: 60s
  scrape_timeout: 30s
  metrics_path: '/metrics'
  static_configs:
    - targets:
        - '10.100.70.250'
  relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: kremers-vmware-exporter.exporters:80

- job_name: 'blackbox-exporter'
  scrape_interval: 30s
  metrics_path: /probe
  params:
    module: [http_2xx] # Look for a HTTP 200 response.
  static_configs:
    - targets:
        - https://gitlab.hostart.az
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: prometheus-community-prometheus-blackbox-exporter.exporters:9115  # blackbox
    - source_labels: [ __meta_dns_name ]
      target_label: __param_hostname  # Make domain name become 'Host' header for probe requests
    - source_labels: [ __meta_dns_name ]
      target_label: vhost  # and store it in 'vhost' label

- job_name: 'mikrotik-exporter'
  scrape_interval: 120s
  scrape_timeout: 120s
  metrics_path: '/metrics'
  static_configs:
    - targets:
        - 'mktxp-exporter.exporters:49090'

- job_name: 'juniper-exporer'
  scrape_interval: 120s
  scrape_timeout: 120s
  static_configs:
    - targets:
        - 172.18.0.35  # Target devices
        - 172.18.0.15
  relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: junos-exporter.exporters:9326  # The junos_exporter's real hostname:port.

#- job_name: 'fortigate_exporter'
#  metrics_path: /probe
#  scrape_interval: 60s
#  scrape_timeout: 120s
#  static_configs:
#    - targets:
#        - https://10.100.70.1
#  relabel_configs:
#    - source_labels: [__address__]
#      target_label: __param_target
#    - source_labels: [__param_target]
#      target_label: instance
#      # Drop the https:// and port (if specified) for the 'instance=' label
#      regex: '(?:.+)(?::\/\/)([^:]*).*'
#    - target_label: __address__
#      replacement: fortigate-exporter.exporters:9710

- job_name: 'snmp-network-devices-exporter'
  static_configs:
    - targets:
        - 172.18.0.10
        - 172.18.0.36
  metrics_path: /snmp
  scrape_interval: 60s
  scrape_timeout: 30s
  params:
    auth: [ public_v2 ]
    module: [ if_mib ]
  relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter.exporters:9116  # The SNMP exporter's real hostname:port.

- job_name: 'snmp-hpe-ilo-exporter'
  scrape_interval: 60s
  scrape_timeout: 30s
  static_configs:
    - targets:
        - 10.100.70.50
        - 10.100.70.60
        - 10.100.70.90
        - 10.100.70.100
        # - 10.100.70.107
        - 10.100.70.130
        - 10.100.70.140
        - 10.100.70.150
        - 10.100.70.160
        - 10.100.70.170
        # - 10.100.70.180
        - 10.100.70.190
        - 10.100.70.200
        - 10.100.70.210
        - 10.100.70.220
        - 94.20.88.155
        - 10.100.100.2
        - 10.100.100.6
  metrics_path: /snmp
  params:
    auth: [ public_ilo_v2 ]
    module: [ hpe ]
  relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter.exporters:9116  # The SNMP exporter's real hostname:port.
